### PR TITLE
Move lerna dependencies to mainlines

### PR DESCRIPTION
**Pull request by Siilwyn**
Move lerna dependencies to mainlines like described in #2.

### CODE REVIEW

**Comment by wizardzloy** [comment]
@Siilwyn could you please resolve the conflict

@jpnelson is the conflict the only reason this PR cannot be merged?

**Comment by wizardzloy** [comment]
@jpnelson @joscha I tested this PR locally, it works. Can we merge this?

**Comment by wizardzloy** [comment]
Don't mind the deleted comment, this PR is broken, since the file structure of `cz-conventional-changelog` is changed, i.e. :

```js
// prompt and format files are not there anymore
import conventionalPrompt from 'cz-conventional-changelog/prompt';
import conventionalFormat from 'cz-conventional-changelog/format';
```

**Comment by Siilwyn** [comment]
❓ I don't get what's going on. "Don't mind the deleted comment", which comment?
What does the FS structure of `cz-conventional-changelog` have to do with this? If it breaks the module why are the tests passing?

**Comment by wizardzloy** [comment]
> If it breaks the module why are the tests passing?

There are no tests here :)

> I don't get what's going on. "Don't mind the deleted comment", which comment?

I added the comment that it works locally for me, but it turned out that I forgot to `npm install` after checking out your branch, that's why I removed that comment, but it still may appear in an email notification or smth.

> What does the FS structure of cz-conventional-changelog have to do with this?

```js
import conventionalPrompt from 'cz-conventional-changelog/prompt';
import conventionalFormat from 'cz-conventional-changelog/format';
```

We have these two imports from `cz-conventional-changelog` in our src/index.js . Files `prompt.js` and `format.js` are not in `cz-conventional-changelog@1.2.0`, that's why it's broken

**Comment by Siilwyn** [comment]
Okay, thank you for the detailed explanation!
Don't worry I don't have email notifications for GH that would be way too much. ^^

**Pull request closed without merging**
